### ISSUE TITLE
[updated v.34] `yarn rw generate scaffold post` fails using latest code

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/redwood#192]
Running latest on redwood `master` and against latest CRA release `…33.01`

Went through all steps in tutorial prior. Running `yarn rw generate scaffold post` resulted in the following:

<img width="498" alt="Screen Shot 2020-03-07 at 3 32 38 PM" src="https://user-images.githubusercontent.com/2951/76153957-e1e63280-6088-11ea-88ca-2419edecd401.png">

Tried again and the process just hangs.

**Comment by cannikin** [comment]
Hmm this seems like what Dominic was seeing in the #general room... he said he resolved by "bumped @prisma/sdk to 0.0.226 from 0.0.222"

**Comment by thedavidprice** [comment]
Shoot. I pushed that update myself — it’s not published but I a _am_ running against master and linked `cli/` package. `yarn.lock` looks updated, too.

I confirmed issue by directly adding to my CRA app `yarn add -W @prisma/sdk`. Still getting an error.

So. Much. Grrr. Sorry RC ☹️

**Comment by cannikin** [comment]
Hmm we need some kind of verbose output to see what’s happening. I can take a look tomorrow.

**Comment by cannikin** [comment]
This failed for me with the latest release, but worked when I linked `cli` to my local copy of `master`. Can we release a version with the latest updates and try again?

**Comment by thedavidprice** [comment]
@cannikin @peterp Using latest .34 packages and CRA 33.0.2, I stepped through the process up to `yarn rw g scaffold post`. Unfortunately the **process still hangs.** :-/

See redwoodjs/create-redwood-app/pull/30 redwoodjs/create-redwood-app/pull/31 for the latest attempts to fix, which worked locally for @cannikin 

You’re our only hope, @peterp

**Comment by peterp** [comment]
I can't reproduce this. I'm still on OS X Mojave, and wondering if this has anything to do with it... I'm going to add a verbose flag to see if we can get any additional output.

**Comment by peterp** [comment]
@thedavidprice Verified that this is now working. When it's stuck it's because the database has not been created yet. `yarn rw db up` should solve that.

Maybe we should check that the database is in the correct state to run the `sdl` commands.

**Comment by victormoukhortov** [comment]
@peterp I'm still having this issue on `0.1.0` - any suggestions?

**Comment by thedavidprice** [comment]
@victormoukhortov replied to you in the forum: https://community.redwoodjs.com/t/experiencing-issue-192-on-v0-1-0-yarn-rw-g-scaffold-post-fails/58/2
