### ISSUE TITLE
Magic Auth - Admin SDK Error

### ISSUE THREAD

**Issue by sean-brydon** [redwoodjs/redwood#4597]
Error:
```
api | 22:33:13 🚨 graphql-server Error building context. Error: Exception in getAuthenticationContext: Magic Admin SDK Error: [ERROR_INCORRECT_SIGNER_ADDR] Incorrect signer address for DID Token. Request failed authentication.
```

I have installed the Magic Link auth provider and I am getting this error whenever the user signs in... Can someone point me in the right direction?

**Comment by thedavidprice** [comment]
Thank you for reporting this @sean-brydon The original Magic link maintainer hasn't updated the provider in quite some time. It's on our list to audit along with verifying all current Auth providers. Unfortunatlye, you might be confirming our suspicion that it's in need of updating.

FYI @dthyresson

**Comment by stephenhandley** [comment]
Not sure if this is the best place to document this, but given that you're planning on that audit figured I'd share what I'm seeing. 
# Token refresh issues (has been happening consistently since 0.39.4) and still issue in latest version
We are running into the following error on our API server whenever a page is left idle in our web app for longer than 15 minutes followed by an additional request being made from the web app page. Refreshing the page fixes things, so my guess is there is some issue with DID token rotation in the client since it expires every 15 minutes
```
Error building context. Error: Exception in getAuthenticationContext: Magic Admin SDK Error: [ERROR_DIDT_EXPIRED] DID Token has expired. Request failed authentication.
 ```

# User denied account access when calling mutation with `skipAuth` directive
Tried upgrading to the latest Redwood version in hopes that it would be addressed but no luck. Previously had no issues with this prior to upgrade. Hitting the following error when trying to call a mutation (with skipAuth directive) where a session refresh error is thrown when running the mutation. Not seeing any logs on the server for the call
```
instrument.js:109 Error: Magic RPC Error: [-32603] Internal error: User denied account access.
    at new ApolloError (index.js:29:1)
    at Object.error (QueryManager.js:137:1)
    at notifySubscription (module.js:137:1)
    at onNotify (module.js:176:1)
    at SubscriptionObserver.error (module.js:229:1)
    at Object.error (asyncMap.js:32:1)
    at notifySubscription (module.js:137:1)
    at onNotify (module.js:176:1)
    at SubscriptionObserver.error (module.js:229:1)
    at iteration.js:4:1
    at Array.forEach (<anonymous>)
    at iterateObserversSafely (iteration.js:4:1)
    at Object.error (Concast.js:36:1)
    at notifySubscription (module.js:137:1)
    at onNotify (module.js:176:1)
    at SubscriptionObserver.error (module.js:229:1)
```
Magic's [documentation](https://magic.link/docs/api-reference/client-side-sdks/web) says that error code is `Internal JSON-RPC error. These can manifest as different generic issues (i.e.: attempting to access a protected endpoint before the user is logged in).`

**Comment by thedavidprice** [comment]
Thanks, all!

@dthyresson looping you in here because no maintainer was assigned. Please do hand on if/as needed.

**Comment by stephenhandley** [comment]
FYI I've gone back to 0.41.0 and no longer seeing that second `-32603` error

**Comment by thedavidprice** [comment]
@Burnsy are you interested/available in ironing out the bugs with the current Magic.link provider? My suspicion is that there's a version mismatch between Redwood Auth package and project packages and/or the Auth.js template is way out of date.

Understood if you aren't able to work on it.

If we don't have a community lead for this, we will need to consider deprecating for v1.

**Comment by thedavidprice** [comment]
FYI Per @dthyresson advice in Discord, he's recommending using Clerk's "email magic links" feature as a replacement for Magic.link. 
- https://clerk.dev/features/email-magic-links
- https://redwoodjs.com/docs/authentication#clerk

We've been very impressed with Clerk's overall DX and features. Additionally, their devs are active in the Redwood community and regularly maintain the RedwoodJS Clerk Auth provider code and docs.

**Comment by stephenhandley** [comment]
Will take a look at a Clerk. Ultimately I'd prefer to avoid a migration at this point. For what its worth I've incrementally upgraded and have identified [0.46.0](https://github.com/redwoodjs/redwood/releases/tag/v0.46.0) as the point where the above `User denied account access when calling mutation with skipAuth directive` error was introduced

**Comment by thedavidprice** [comment]
Thanks @stephenhandley 💯understood about avoiding a migration. Because there was a fix for Auth in [v0.46.1](https://github.com/redwoodjs/redwood/releases/tag/v0.46.1), wondering if you tried it as well.

Lastly, the most recent version of Redwood used magic-sdk ^8 and magic-sdk/admin ^1.3 Have you confirmed you are using compatible versions in web/package.json?

**Comment by stephenhandley** [comment]
@thedavidprice I bumped versions and still seeing the `instrument.js:109 Error: Magic RPC Error: [-32603] Internal error: User denied account access.`

**Comment by Burnsy** [comment]
I would love to get to it but i am so busy! let me ask in the magic community if anyone wants to jump in to help finish it and get it up  to spec

**Comment by shahbaz17** [comment]
> Error:
> 
> ```
> api | 22:33:13 🚨 graphql-server Error building context. Error: Exception in getAuthenticationContext: Magic Admin SDK Error: [ERROR_INCORRECT_SIGNER_ADDR] Incorrect signer address for DID Token. Request failed authentication.
> ```
> 
> I have installed the Magic Link auth provider and I am getting this error whenever the user signs in... Can someone point me in the right direction?

Hey @sean-brydon 

I am Shahbaz, one of the Dev Advocates [@Magic](https://magic.link) and I have worked on updating the Magic Auth implementation here at RedwooJS.

Before starting the PR to fix this, can you please confirm the following:
* Are you using the `PUBLISHABLE API KEY` and `SECRET KEY` from the same application?

Thanks

**Comment by dthyresson** [comment]
Thanks @shahbaz17 for picking this up so we can have an update ahead of v1.0

**Comment by stephenhandley** [comment]
yes thanks @shahbaz17, could you also please take a look at these issues, they're separate from the one in the issue title/description: https://github.com/redwoodjs/redwood/issues/4597#issuecomment-1058490585

**Comment by stephenhandley** [comment]
@thedavidprice tracked down the issue with magic link token expiry here: https://github.com/redwoodjs/redwood/pull/4956

**Comment by jtoar** [comment]
Hey everyone, I know there may be more work to do in general but okay to close this issue out?

**Comment by stephenhandley** [comment]
@jtoar yes the two issues I mentioned above have been resolved and we aren't seeing them on 1.0.0. Not sure about the original issue @sean-brydon opened, but my read of that was there was probably a token mismatch issue at play.

**Comment by sean-brydon** [comment]
I'm sorry - i completely forgot i opened this issue and it got a bit lost within my github... I will give this ago tomorrow and see if im still having the issue. @shahbaz17

**Comment by jtoar** [comment]
Thanks @stephenhandley and no worries @sean-brydon, give it a go and let us know, thanks a ton!

**Comment by jtoar** [comment]
Will close this for now as things seem resolved but happy to reopen.

**Comment by Abhishek7Tech** [comment]
AnyOne help please 
Magic Admin SDK Error: [SERVICE_ERROR] A service error occurred while communicating with the Magic API. Check the `data` key of this error object to see nested errors with additional context.

**Comment by Ounza** [comment]
Having the same issue as @Abhishek7Tech above.

**Comment by connect2d** [comment]
Experiencing the same issue. as @Abhishek7Tech and @Ounza mentioned. we have reached out to customer support. they have suggested to change delete the app and create a new one. but still the same issue keep popping.

**Comment by dthyresson** [comment]
Magic auth no longer supported
