### ISSUE TITLE
[Bug?]: Typing broken for queryResult prop in Cells

### ISSUE THREAD

**Issue by shivghai** [redwoodjs/redwood#8179]
### What's not working?

I can see that `queryResult` actually works, but typescript is complaining

error TS2339: Property 'queryResult' does not exist on type 'Partial<Omit<QueryOperationResult<TraceMatrixQuery, any>, "data" | "error" | "loading"> & { updating: boolean; }> & { ...; } & Exact<...>'.

37   queryResult: { refetch },

### How do we reproduce the bug?

Just use typescript + `queryResult`

### What's your environment? (If it applies)

```shell
System:
    OS: macOS 12.5
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /private/var/folders/8y/99byt5ms31d1z8jgjfmyvcg80000gn/T/xfs-90261060/node
    Yarn: 3.2.1 - /private/var/folders/8y/99byt5ms31d1z8jgjfmyvcg80000gn/T/xfs-90261060/yarn
  Databases:
    SQLite: 3.37.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 110.0
    Safari: 15.6
  npmPackages:
    @redwoodjs/auth-auth0-setup: 5.0.2 => 5.0.2 
    @redwoodjs/core: 5.0.2 => 5.0.2
```

### Are you interested in working on this?

- [ ] I'm interested in working on this

**Comment by pvenable** [comment]
I was going to file this issue too, but since this is already here I'll add to it:

In addition to the reported issue regarding `queryResult`, Cell typings also don't seem to have been updated for https://github.com/redwoodjs/redwood/pull/7704.  `CellSuccessData` still treats all graphql fields as ["guaranteed"](https://github.com/redwoodjs/redwood/blob/ca2ebcfa9b2c57046dd1b87bf885f79e76acba67/packages/web/src/components/createCell.tsx#L76-L96) despite the behavior change in which `Success` may be rendered with partial data.  With that change, it seems it would only be appropriate to "guarantee" the presence of data in the single-field case, if at all.

**Comment by jtoar** [comment]
@shivghai I just published a patch that fixes `queryResult` here: https://github.com/redwoodjs/redwood/releases/tag/v5.0.3. Tagging the PR as well: https://github.com/redwoodjs/redwood/pull/8175. Could you try it out and let me know if it works for you?

@pvenable great point, I'll take a look at that now.

**Comment by pvenable** [comment]
> Could you try it out and let me know if it works for you?

@jtoar 5.0.3 solved the `queryResult` typing issue for me. 👍 Thanks!

> I'll take a look at that now

Awesome -- some `CellSuccessData` typing improvements will definitely help make some bugs impossible to ship. 🙂👍

**Comment by shivghai** [comment]
Looks like some props within `queryResult` are still broken (i'm looking for `refetch`). @jtoar let me know if I should create a new issue for this

**Comment by jtoar** [comment]
@shivghai I think this issue is ok to track this in. I can see them in a project I just made (this is v5.0.6, but the type fix was shipped in v5.0.3): 

<img width="907" alt="image" src="https://github.com/redwoodjs/redwood/assets/32992335/199c4d56-1408-4290-a11a-cbf6e17fe32f">

I may need more steps to reproduce. Have you changed anything about the setup? What types do you see?

**Comment by shivghai** [comment]
whoops never mind - looks like it's working. sorry about that!
