### ISSUE TITLE
Running yarn rw test should automatically generate jest.config.js files for api and web if they're missing

### ISSUE THREAD

**Issue by Terris** [redwoodjs/redwood#907]
**EDIT:** The original issue is solved by adding jest.config.js files. So, running `yarn rw test` should automatically generate jest.config.js files for api and web if they're missing.

Original issue: Tests [web] are failing to run because __REDWOOD__API_PROXY_PATH is not defined
```bash
yarn rw test web

Test suite failed to run

    ReferenceError: __REDWOOD__API_PROXY_PATH is not defined

    > 1 | import { render } from '@redwoodjs/testing'
        | ^
      2 | 
      3 | import { Header } from './Header'
      4 | 

      at Object.<anonymous> (../node_modules/@redwoodjs/web/dist/config.js:5:36)
      at Object.<anonymous> (../node_modules/@redwoodjs/web/dist/index.js:68:1)
      at Object.<anonymous> (../node_modules/@redwoodjs/testing/dist/MockProviders.js:15:12)
      at Object.<anonymous> (../node_modules/@redwoodjs/testing/dist/customRender.js:17:22)
      at Object.<anonymous> (../node_modules/@redwoodjs/testing/dist/index.js:78:21)
      at Object.<anonymous> (src/components/Header/Header.test.js:1:1)
`

```bash
yarn rw info

yarn run v1.22.4
$ /Users/terriskremer/Sites/kremer/kremerlibrary/node_modules/.bin/rw info

  System:
    OS: macOS Mojave 10.14.6
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.1 - /var/folders/s3/jyccmmxs11j893bfb92tt0900000gn/T/yarn--1596039261212-0.9150607551937429/node
    Yarn: 1.22.4 - /var/folders/s3/jyccmmxs11j893bfb92tt0900000gn/T/yarn--1596039261212-0.9150607551937429/yarn
  Databases:
    SQLite: 3.24.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 74.0
    Safari: 13.1.2
  npmPackages:
    @redwoodjs/core: ^0.14.0 => 0.14.0

**Comment by peterp** [comment]
Hey @Terris, thanks for opening this issue, I'm pretty sure this should be fixed in the latest canary - and we're going to release 0.15.0 very soon.

**Comment by Terris** [comment]
Tests still failing with the same error above after upgrade to 0.15.0.

**Comment by peterp** [comment]
@Terris Could you share you code with me?

**Comment by Terris** [comment]
[https://github.com/Terris/kremerlibrary](https://github.com/Terris/kremerlibrary) Thanks, so much @peterp! I know you're busy.

**Comment by peterp** [comment]
No worries! I'm only busy because people use the framework :)

I think you may need to create a `jest.config.js` in the `web` and `api` folders; the instructions for doing so are over here:

https://github.com/redwoodjs/redwood/releases/tag/v0.14.0

**Comment by peterp** [comment]
If this turns out to be the case, let's change this issue, and make is so that `yarn rw test` automatically creates those files for you if they're missing.

**Comment by Terris** [comment]
@peterp That was it. Many thanks. I've updated the issue.

**Comment by peterp** [comment]
Thanks @Terris - My bad for not catching this earlier... and for not making it clear that those configs are required.

**Comment by thedavidprice** [comment]
Recommending we resolve this via #4096
